version: '3'

services:
  proxy:
    image: traefik
    container_name: traefik
    command: --web --docker --docker.domain=domain.local --logLevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - dmz
      - frontoffice
    labels:
      - "traefik.frontend.rule=Host:traefik.domain.local"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=gogs_dmz"

  web:
    image: gogs/gogs
    container_name: web
    volumes:
      - data:/home/git/gogs-repositories
    networks:
      - frontoffice
      - backoffice
    labels:
      - "traefik.frontend.rule=Host:gogs.domain.local"
      - "traefik.backend=web"
      - "traefik.port=3000"
      - "traefik.docker.network=gogs_frontoffice"

  db:
    image: percona/percona-server
    container_name: mysql_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gogs
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "10022:22"
    networks:
      - backoffice
    labels:
      - "traefik.enable=false"

networks:
    dmz:
      driver: bridge
    frontoffice:
      driver: bridge
    backoffice:
      driver: bridge

volumes:
    data:
    db:
